import { GuideLinks } from "../../components/guide-links";
import { englishMetadata } from "../../../lib/seo";
import { AdPanel } from "../../components/ad-panel";
import { SiteFooter, SiteHeader } from "../../components/site-shell";

export const metadata = englishMetadata("support", "Duplicate File Safety Guide & Support", "Learn how to analyze local duplicates, protect software projects, organize photos and videos, and verify folders or backups without guessing which files are disposable.");

export default function Page() {
  return <main lang="en"><SiteHeader pagePath="support" locale="en" /><article className="legal shell"><h1>Understand purpose before removing a copy.</h1><p className="lead">Identical content is evidence of a duplicate candidate, not evidence that another location is unnecessary.</p><h2>Start with the read-only browser analyzer</h2><p>Choose one clear folder and review exact matches without uploading or deleting files. For large libraries or actual cleanup, use the Windows app. Network and removable storage may not support the Windows Recycle Bin.</p><h2>Protect software projects and working folders</h2><p>Independent projects often require identical configuration, dependency and plug-in files. Detected project markers, package folders and virtual environments are excluded in Windows; review custom workflows manually. Add important working subfolders to protection before cleanup.</p><h2>Organize photos and videos by impact</h2><p>Review the largest media groups first. DUPESPACE displays one representative image where possible and keeps duplicate rows lightweight to avoid decoding the same content repeatedly.</p><h2>Verify folders and backups</h2><p>Windows can identify duplicate folder mirrors using relative paths, sizes and content fingerprints. Browser backup-integrity verification is not currently included. Empty folders, links and unverifiable items are excluded. Any change between analysis and action cancels the operation.</p><h2>Use recoverable cleanup</h2><p>Start with a small test and use the Windows Recycle Bin. Failures are reported and never become permanent deletion. Keep audit reports private because they may contain filenames and paths.</p><h2>Report a problem safely</h2><p>Use <a href="https://github.com/kaimeow1114-netizen/dupespace-duplicate-file-cleaner/issues">GitHub Issues</a> with the app version, reproduction steps and a redacted error. Never post credentials, private filenames or an unredacted CSV.</p></article><GuideLinks locale="en" /><AdPanel /><SiteFooter locale="en" /></main>;
}
