import { FileCheck2, FileWarning, FolderSync, ScanSearch, ShieldCheck } from "lucide-react";
import { englishMetadata } from "../../../lib/seo";
import { MergeAnalyzer } from "../../components/merge-analyzer";
import { SiteFooter, SiteHeader } from "../../components/site-shell";

export const metadata = englishMetadata("merge", "Compare Folders Before Merging — Find Renamed Duplicates & Conflicts", "Compare two folders locally before merging. Find exact files with different names, missing files, and same-path version conflicts without uploading or changing anything.");

export default function EnglishMergePage() {
  return <main className="merge-page" lang="en"><SiteHeader locale="en" pagePath="merge" privateWorkspace /><section className="merge-intro"><div className="shell"><span className="eyebrow light"><FolderSync size={16} aria-hidden="true" /> SAFE MERGE PREVIEW</span><h1>See the differences <span className="gradient-text">before you merge.</span></h1><p>Find exact content under a different name, files not yet imported, and same-path version conflicts. Every comparison stays on this device.</p><span className="merge-intro-trust"><ShieldCheck size={16} aria-hidden="true" />Read-only preview. Only the two folders you choose can be read.</span></div></section><div className="shell merge-wrap"><MergeAnalyzer locale="en" /></div><section className="shell merge-explainer"><div><span className="eyebrow">WHY COMPARE FIRST</span><h2>Three problems a normal folder merge can hide</h2><p>Drag-and-drop overwrite prompts reveal filename collisions. Content comparison reveals the actual relationship before anything changes.</p></div><div className="merge-explainer-grid"><article><ScanSearch aria-hidden="true" /><h3>Renamed files can still be identical</h3><p>Complete content fingerprints find the same photo, video or document after its name or subfolder changes.</p></article><article><FileWarning aria-hidden="true" /><h3>The same name can hide a new version</h3><p>Different content at the same relative path is classified as a version conflict, without guessing from a date or filename.</p></article><article><FileCheck2 aria-hidden="true" /><h3>Take a read-only result with you</h3><p>The page never copies or deletes. Review both paths first, then export a CSV record of the comparison.</p></article></div></section><SiteFooter locale="en" /></main>;
}
