import { productFaq } from "../../lib/product-copy";
import { GuideLinks } from "../components/guide-links";
import { headers } from "next/headers";
import { englishMetadata } from "../../lib/seo";
import { AdPanel } from "../components/ad-panel";
import { HeroDashboard } from "../components/hero-dashboard";
import { SiteFooter, SiteHeader } from "../components/site-shell";
import { ArrowRight, CheckCircle2, Code2, FileCheck2, FileSearch, FolderLock, HardDriveDownload, Images, LockKeyhole, ShieldCheck } from "lucide-react";

export const metadata = englishMetadata("", "Local Duplicate File Finder & Windows Cleaner", "Find exact duplicate files without uploading filenames, paths or contents. Use the read-only browser analyzer or the free open-source Windows cleaner with protected copies and CSV audit reports.");

const faq = productFaq.en;

export default async function EnglishHome() {
  const nonce = (await headers()).get("x-dupespace-nonce") ?? undefined;
  return <main lang="en">
    <script suppressHydrationWarning nonce={nonce} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "DUPESPACE", url: "https://dupespace.app/en/", applicationCategory: "UtilitiesApplication", operatingSystem: "Web, Windows 10, Windows 11", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: "Local duplicate analysis, Windows duplicate cleanup, exact image and video duplicate analysis, CSV reports" },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(({ question: name, answer: text }) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    ]) }} />
    <SiteHeader locale="en" />
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> FREE · OPEN SOURCE · LOCAL-FIRST</span><h1><span className="headline-line">Understand your files.</span><span className="headline-line gradient-text">Reclaim space with confidence.</span></h1><p className="hero-english">Find duplicate files. Keep what matters.</p><p className="purpose-statement"><strong>DUPESPACE is a free, open-source duplicate file finder and cleaner.</strong> Analyze a folder in your browser without an account or upload. To remove unwanted copies, review their paths in the Windows app and move them to the Recycle Bin.</p><div className="hero-actions"><a className="button primary" href="/en/local/"><span>Analyze a local folder</span><ArrowRight size={18} aria-hidden="true" /></a><a className="button secondary" href="/en/download/"><HardDriveDownload size={18} aria-hidden="true" /><span>Download for Windows</span></a></div><div className="trust-row"><span><CheckCircle2 size={14} aria-hidden="true" />No upload</span><span><CheckCircle2 size={14} aria-hidden="true" />Read-only web report</span><span><CheckCircle2 size={14} aria-hidden="true" />Keep at least one copy</span><a href="/en/privacy/">Privacy policy</a></div></div><div className="hero-dashboard-wrap"><HeroDashboard locale="en" /></div></div></section>
    <section className="stats-strip"><div className="shell stats-grid"><div><strong>0</strong><span>Files uploaded</span></div><div><strong>2</strong><span>Browser analysis / Windows cleanup</span></div><div><strong>1+</strong><span>Copies kept per group</span></div><div><strong>0</strong><span>Web deletion permission</span></div></div></section>
    <section className="section feature-band" id="features"><div className="shell"><div className="section-heading"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> THREE PRODUCT PILLARS</span><h2>Focused tools for problems people actually feel.</h2><p>Start with exact duplicate analysis and Windows cleanup. Media organization and backup verification are future directions, not features included in the current browser analyzer.</p></div><div className="download-safety-grid"><article><FileSearch aria-hidden="true" /><h3>Exact duplicate analysis</h3><p>Filter by size, compare content and review every path. Browser analysis is read-only; Windows cleanup is recoverable by default.</p></article><article><Images aria-hidden="true" /><h3>Photo and video organization · roadmap</h3><p>Today: exact duplicate groups with lightweight image previews. Planned: richer media organization; similar-looking photos are not treated as exact duplicates.</p></article><article><FileCheck2 aria-hidden="true" /><h3>Folder and backup verification · roadmap</h3><p>Planned: compare relative paths, sizes and fingerprints to find missing or changed files. The current browser analyzer finds exact duplicate files; it does not certify backups.</p></article></div></div></section>
    <section className="section alternate"><div className="shell split"><div><span className="eyebrow light">HOW IT WORKS</span><h2>Compare file content, not just names.</h2><p>The browser narrows candidates by size, then computes chunked content fingerprints entirely on your device. The Windows app is designed for large libraries and protected, recoverable cleanup. Matching content is a candidate, never proof that another path has no purpose.</p><a className="button mint" href="/en/support/">Read the safety guide</a></div><ol className="steps"><li><span>01</span><div><b>Choose</b><small>Select only the folder you want to analyze</small></div></li><li><span>02</span><div><b>Compare</b><small>Compute local content fingerprints</small></div></li><li><span>03</span><div><b>Organize</b><small>Export a report or use Windows cleanup</small></div></li></ol></div></section>
    <section className="section privacy-band"><div className="shell privacy-feature"><div><span className="eyebrow"><LockKeyhole size={15} aria-hidden="true" /> LOCAL-FIRST PRIVACY</span><h2>Your files stay on your device.</h2><p>The analyzer does not require an account and does not upload filenames, paths or file contents. Your file list and results stay on this device. The analyzer cannot move or delete files.</p><div className="privacy-actions"><a className="button primary" href="/en/local/">Open local analyzer</a><a className="text-link" href="/en/privacy/">Read the privacy policy</a></div></div><div className="privacy-card"><b>No account. No upload. No deletion permission.</b><p>Only files explicitly handed to the browser file picker are available to the page. Close the tab to clear unexported in-memory results.</p></div></div></section>
    <section className="section trust-section"><div className="shell"><div className="section-heading"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> WHY TRUST DUPESPACE</span><h2>Read the code. Verify the claims.</h2></div><div className="download-safety-grid"><article><ShieldCheck aria-hidden="true" /><h3>Clear boundaries</h3><p>Web analysis is read-only. Windows protects projects, selected subfolders and at least one keeper per group.</p></article><article><FolderLock aria-hidden="true" /><h3>Purpose before matching</h3><p>Identical content does not prove a copy is disposable. Context and protection rules come before removal.</p></article><article><Code2 aria-hidden="true" /><h3>Free and open source</h3><p>Inspect the implementation, report issues or run your own copy under the MIT License.</p><a href="https://github.com/kaimeow1114-netizen/dupespace-duplicate-file-cleaner">View source on GitHub</a></article></div></div></section>
    <section className="section faq-band" id="faq"><div className="shell"><h2>Frequently asked questions</h2>{faq.map(({ question, answer }) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <GuideLinks locale="en" />
    <AdPanel />
    <SiteFooter locale="en" />
  </main>;
}
