import { productFaq } from "../../lib/product-copy";
import { GuideLinks } from "../components/guide-links";
import { headers } from "next/headers";
import { englishMetadata } from "../../lib/seo";
import { AdPanel } from "../components/ad-panel";
import { HeroDashboard } from "../components/hero-dashboard";
import { StorageIntelligenceMotion } from "../components/lower-page-motion";
import { SiteFooter, SiteHeader } from "../components/site-shell";
import { ArrowRight, CheckCircle2, Code2, FileCheck2, FileSearch, FolderLock, Layers3, LockKeyhole, ShieldCheck } from "lucide-react";

export const metadata = englishMetadata("", "Compare Folders & Find Renamed Duplicate Files", "Compare two folders before merging. Find identical content under different names, missing files and same-path version conflicts locally, without an account or upload.");

const faq = productFaq.en;

export default async function EnglishHome() {
  const nonce = (await headers()).get("x-dupespace-nonce") ?? undefined;
  return <main lang="en">
    <script suppressHydrationWarning nonce={nonce} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "DUPESPACE", url: "https://dupespace.app/en/", applicationCategory: "UtilitiesApplication", operatingSystem: "Web, Windows 10, Windows 11", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: "Folder merge preview, renamed duplicate detection, same-path version conflict detection, local duplicate analysis, Windows recoverable cleanup, CSV reports" },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(({ question: name, answer: text }) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    ]) }} />
    <SiteHeader locale="en" />
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> FREE · OPEN SOURCE · LOCAL-FIRST</span><h1><span className="headline-line">Understand two folders.</span><span className="headline-line gradient-text">Merge without the guesswork.</span></h1><p className="hero-english">Find renamed duplicates. Prevent merge mistakes.</p><p className="purpose-statement"><strong>DUPESPACE is a free, open-source folder merge preview and duplicate file tool.</strong> Find exact content under different names, files missing from either side, and same-path version conflicts. Files are read on-device and never sent to a DUPESPACE server.</p><div className="hero-actions"><a className="button primary" href="/en/merge/"><span>Compare two folders</span><ArrowRight size={18} aria-hidden="true" /></a><a className="button secondary" href="/en/local/"><FileSearch size={18} aria-hidden="true" /><span>Find duplicates in one folder</span></a></div><div className="trust-row"><span><CheckCircle2 size={14} aria-hidden="true" />Renamed matches</span><span><CheckCircle2 size={14} aria-hidden="true" />Version conflicts</span><span><CheckCircle2 size={14} aria-hidden="true" />Never sent to a server</span><a href="/en/privacy/">Privacy policy</a></div></div><div className="hero-dashboard-wrap"><HeroDashboard locale="en" /></div></div></section>
    <section className="stats-strip"><div className="shell stats-grid"><div><strong>2</strong><span>Folders compared side by side</span></div><div><strong>5</strong><span>Clear merge categories</span></div><div><strong>0</strong><span>Files sent to a server</span></div><div><strong>0</strong><span>Web write permission</span></div></div></section>
    <section className="section feature-band" id="features"><div className="shell"><div className="section-heading"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> MERGE WITH CONTEXT</span><h2>A merge map for problems filenames cannot explain.</h2><p>A different name can hide identical content. The same relative path can hide a different version. DUPESPACE separates both before you copy or overwrite anything.</p></div><div className="download-safety-grid"><article><Layers3 aria-hidden="true" /><h3>Two-folder merge preview</h3><p>Compare incoming and destination folders for exact matches, one-sided files and same-path conflicts.</p></article><article><FileSearch aria-hidden="true" /><h3>Renamed duplicate detection</h3><p>Complete content fingerprints find identical files even when the names and folder locations changed.</p></article><article><FileCheck2 aria-hidden="true" /><h3>Purpose-aware review</h3><p>Project, application and backup contexts are flagged because identical bytes can still serve different roles.</p></article></div></div></section>
    <section className="section alternate"><div className="shell split"><div><span className="eyebrow light">HOW IT WORKS</span><h2>Compare actual content, not just names.</h2><p>Choose an incoming folder and a destination. DUPESPACE narrows candidates by size and sample, then verifies complete content locally. The result separates exact matches, renamed or moved matches, new files and version conflicts.</p><a className="button mint" href="/en/merge/">Open merge preview</a></div><ol className="steps"><li><span>01</span><div><b>Choose</b><small>Select incoming and destination folders</small></div></li><li><span>02</span><div><b>Verify</b><small>Match full content on this device</small></div></li><li><span>03</span><div><b>Review</b><small>See the merge map and export CSV</small></div></li></ol></div></section>
    <section className="section privacy-band"><div className="shell privacy-feature"><div><span className="eyebrow"><LockKeyhole size={15} aria-hidden="true" /> LOCAL-FIRST PRIVACY</span><h2>Your files stay on your device.</h2><p>No account is required. Choosing a folder grants this tab on-device read access; files are not sent to a DUPESPACE server, and the page cannot copy, overwrite or delete them.</p><div className="privacy-actions"><a className="button primary" href="/en/merge/">Preview a folder merge</a><a className="text-link" href="/en/privacy/">Read the privacy policy</a></div></div><div className="privacy-card"><b>No server transfer. No write permission.</b><p>Only files explicitly handed to the browser file picker are available to the page. Close the tab to clear unexported in-memory results.</p></div></div></section>
    <section className="section trust-section"><div className="shell"><div className="section-heading"><span className="eyebrow"><ShieldCheck size={15} aria-hidden="true" /> WHY TRUST DUPESPACE</span><h2>Read the code. Verify the claims.</h2></div><div className="download-safety-grid"><article><ShieldCheck aria-hidden="true" /><h3>Clear boundaries</h3><p>Web analysis is read-only. Windows protects projects, selected subfolders and at least one keeper per group.</p></article><article><FolderLock aria-hidden="true" /><h3>Purpose before matching</h3><p>Identical content does not prove a copy is disposable. Context and protection rules come before removal.</p></article><article><Code2 aria-hidden="true" /><h3>Free and open source</h3><p>Inspect the implementation, report issues or run your own copy under the MIT License.</p><a href="https://github.com/kaimeow1114-netizen/dupespace-duplicate-file-cleaner">View source on GitHub</a></article></div></div></section>
    <section className="section faq-band" id="faq"><div className="shell"><h2>Frequently asked questions</h2>{faq.map(({ question, answer }) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="section retention-band" id="insights"><div className="shell retention-section"><div className="section-heading"><span className="eyebrow"><FileSearch size={15} aria-hidden="true" /> FILE INTELLIGENCE</span><h2>Not another duplicate list. A merge map you can act on.</h2><p>Byte equality does not prove two files serve the same purpose. DUPESPACE narrows candidates, verifies complete content, then separates version conflicts, context risks and renamed exact matches.</p></div><StorageIntelligenceMotion locale="en" /></div></section>
    <GuideLinks locale="en" />
    <AdPanel />
    <SiteFooter locale="en" />
  </main>;
}
